export {default as VehicleList} from './VehicleList';
export {default as AddDriver} from './AddDriver';
export {default as AddEmployee} from './AddEmployee';
export {default as AddGeofence} from './AddGeofence';
export {default as AddVehicles} from './AddVehicles';
export {default as CompletedTrip} from './CompletedTrip';
export {default as CreateNewTrip} from './CreateNewTrip';
export {default as PreviouseTrip} from './PreviouseTrip';
export {default as DriverList} from './DriverList';
export {default as EmployeeList} from './EmployeeList';
export {default as GeneralSetting} from './GeneralSetting';
export {default as GeofenceEvent} from './GeofenceEvent';
export {default as HistoryOfTracking} from './HistoryOfTracking';
export {default as IncomeAndExpeense} from './IncomeAndExpeense';
export {default as InprogressTrip} from './InprogressTrip';
export {default as LiveLocation} from './LiveLocation';
export {default as Notification} from './Notification';
export {default as VehicleDetail} from './VehicleDetail';
export {default as DriverDetail} from './DriverDetail';
export { default as EmployeeDetail } from './EmployeeDetail';
export { default as UrgentTripForm } from './UrgentTripForm';
export { default as LongTrip } from './LongTrip';
